# These are supported funding model platforms

github: [RedStar071]
patreon: WolfStarBot
open_collective: # Replace with a single Open Collective username
ko_fi: redstar071
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://donate.wolfstar.rocks/paypal']
