packages:
    - 'projects/*'

ignoredBuiltDependencies:
    - bufferutil
    - zlib-sync

onlyBuiltDependencies:
    - '@prisma/client'
    - '@prisma/engines'
    - prisma

overrides:
    ansi-regex: ^5.0.1
    discord-api-types: ^0.38.34
    minimist: ^1.2.6
    vite: ^6.3.5

dedupePeers: true

shellEmulator: true
