packages:
  - 'projects/*'

allowBuilds:
  bufferutil: false
  'zlib-sync': false
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: false

overrides:
  ansi-regex: ^5.0.1
  discord-api-types: ^0.38.34
  minimist: ^1.2.6
  vite: ^6.3.5

dedupePeers: true

shellEmulator: true

minimumReleaseAge: 0
