import type { ReadonlyGuildData } from '#lib/database/settings/types';

let cachedDefaultGuildSettings: DefaultGuildData | null = null;

/**
 * The settings a guild has before anything is written for it. The values mirror the column defaults of the Prisma 8
 * contract; the columns without a default (the auto-moderation actions and thresholds) use the ones the bot ships with.
 */
export function getDefaultGuildSettings() {
	cachedDefaultGuildSettings ??= Object.assign(Object.create(null), {
		language: 'en-US',
		modulesAutomod: true,
		modulesModeration: true,
		modulesLogs: true,
		modulesCommands: true,
		modulesRoles: true,
		automodChannel: null,
		automodTrackNative: false,
		selfmodAttachmentsEnabled: false,
		selfmodAttachmentsSoftAction: 0,
		selfmodAttachmentsHardAction: 'Warning',
		selfmodAttachmentsHardActionDuration: null,
		selfmodAttachmentsThresholdMaximum: 10,
		selfmodAttachmentsThresholdDuration: 60000,
		selfmodAttachmentsIgnoredRoles: [],
		selfmodAttachmentsIgnoredChannels: [],
		selfmodCapitalsEnabled: false,
		selfmodCapitalsSoftAction: 0,
		selfmodCapitalsHardAction: 'Warning',
		selfmodCapitalsHardActionDuration: null,
		selfmodCapitalsThresholdMaximum: 10,
		selfmodCapitalsThresholdDuration: 60000,
		selfmodCapitalsMinimum: 15,
		selfmodCapitalsMaximum: 50,
		selfmodCapitalsIgnoredRoles: [],
		selfmodCapitalsIgnoredChannels: [],
		selfmodInvitesEnabled: false,
		selfmodInvitesSoftAction: 0,
		selfmodInvitesHardAction: 'Warning',
		selfmodInvitesHardActionDuration: null,
		selfmodInvitesThresholdMaximum: 10,
		selfmodInvitesThresholdDuration: 60000,
		selfmodInvitesAllowedCodes: [],
		selfmodInvitesAllowedGuilds: [],
		selfmodInvitesIgnoredRoles: [],
		selfmodInvitesIgnoredChannels: [],
		selfmodLinksEnabled: false,
		selfmodLinksSoftAction: 0,
		selfmodLinksHardAction: 'Warning',
		selfmodLinksHardActionDuration: null,
		selfmodLinksThresholdMaximum: 10,
		selfmodLinksThresholdDuration: 60000,
		selfmodLinksAllowed: [],
		selfmodLinksIgnoredRoles: [],
		selfmodLinksIgnoredChannels: [],
		selfmodMentionsEnabled: false,
		selfmodMentionsSoftAction: 0,
		selfmodMentionsHardAction: 'Warning',
		selfmodMentionsHardActionDuration: null,
		selfmodMentionsThresholdMaximum: 10,
		selfmodMentionsThresholdDuration: 60000,
		selfmodMentionsIgnoredRoles: [],
		selfmodMentionsIgnoredChannels: [],
		selfmodMentionsOverrides: [],
		selfmodNewlinesEnabled: false,
		selfmodNewlinesSoftAction: 0,
		selfmodNewlinesHardAction: 'Warning',
		selfmodNewlinesHardActionDuration: null,
		selfmodNewlinesThresholdMaximum: 10,
		selfmodNewlinesThresholdDuration: 60000,
		selfmodNewlinesMaximum: 20,
		selfmodNewlinesIgnoredRoles: [],
		selfmodNewlinesIgnoredChannels: [],
		noMentionSpamEnabled: false,
		noMentionSpamSoftAction: 0,
		noMentionSpamHardAction: 'Warning',
		noMentionSpamHardActionDuration: null,
		noMentionSpamThresholdMaximum: 10,
		noMentionSpamThresholdDuration: 60000,
		noMentionSpamAlerts: false,
		noMentionSpamMentionsAllowed: 20,
		noMentionSpamTimePeriod: 8,
		noMentionSpamIgnoredRoles: [],
		noMentionSpamIgnoredChannels: [],
		selfmodWordsEnabled: false,
		selfmodWordsSoftAction: 0,
		selfmodWordsHardAction: 'Warning',
		selfmodWordsHardActionDuration: null,
		selfmodWordsThresholdMaximum: 10,
		selfmodWordsThresholdDuration: 60000,
		selfmodWordsList: [],
		selfmodWordsIgnoredRoles: [],
		selfmodWordsIgnoredChannels: [],
		commandsDisabled: [],
		commandsDisabledChannels: [],
		commandsDisabledInChannels: [],
		logsMemberAdd: null,
		logsMemberRemove: null,
		logsMemberNicknameUpdate: null,
		logsMemberUsernameUpdate: null,
		logsMessageDelete: null,
		logsMessageDeleteNsfw: null,
		logsMessageUpdate: null,
		logsMessageUpdateNsfw: null,
		logsPrune: null,
		logsReaction: null,
		logsRoleCreate: null,
		logsRoleUpdate: null,
		logsRoleDelete: null,
		logsChannelCreate: null,
		logsChannelUpdate: null,
		logsChannelDelete: null,
		logsEmojiCreate: null,
		logsEmojiUpdate: null,
		logsEmojiDelete: null,
		logsEmojiAdd: null,
		logsEmojiAddIncludeTwemoji: false,
		logsServerUpdate: null,
		logsCommand: null,
		logsSettings: null,
		logsIgnoreAll: [],
		logsIgnoreMessages: [],
		logsIgnoreReactions: [],
		moderationChannel: null,
		moderationTrackBans: false,
		moderationTrackTimeouts: false,
		permissionsUsers: [],
		permissionsRoles: [],
		rolesInitial: [],
		rolesInitialHumans: [],
		rolesInitialRobots: [],
		rolesAdmin: [],
		rolesModerator: [],
		rolesMuted: null,
		rolesPublic: [],
		rolesRemoveInitial: false,
		rolesUniqueRoleSets: [],
		rolesRestrictedReaction: null,
		rolesRestrictedEmbed: null,
		rolesRestrictedEmoji: null,
		rolesRestrictedAttachment: null,
		rolesRestrictedVoice: null
	} as const satisfies DefaultGuildData);

	return cachedDefaultGuildSettings;
}

export type DefaultGuildData = Omit<ReadonlyGuildData, 'id'>;
