import type { ReadonlyGuildData } from './types.js';

let cachedDefaultGuildSettings: DefaultGuildData | null = null;

/**
 * The settings a guild has before anything is written for it. The values mirror the column defaults of the Prisma 8
 * contract; the columns without a default (the auto-moderation actions and thresholds) use the ones the bot ships with.
 */
export function getDefaultGuildSettings() {
	cachedDefaultGuildSettings ??= Object.assign(Object.create(null), {
		language: 'en-US',
		modulesAutomod: true,
		modulesModeration: true,
		modulesLogs: true,
		modulesCommands: true,
		modulesRoles: true,
		automodChannel: null,
		automodTrackNative: false,
		automodAttachmentsEnabled: false,
		automodAttachmentsSoftAction: 0,
		automodAttachmentsHardAction: 'Warning',
		automodAttachmentsHardActionDuration: null,
		automodAttachmentsThresholdMaximum: 10,
		automodAttachmentsThresholdDuration: 60000,
		automodAttachmentsIgnoredRoles: [],
		automodAttachmentsIgnoredChannels: [],
		automodCapitalsEnabled: false,
		automodCapitalsSoftAction: 0,
		automodCapitalsHardAction: 'Warning',
		automodCapitalsHardActionDuration: null,
		automodCapitalsThresholdMaximum: 10,
		automodCapitalsThresholdDuration: 60000,
		automodCapitalsMinimum: 15,
		automodCapitalsMaximum: 50,
		automodCapitalsIgnoredRoles: [],
		automodCapitalsIgnoredChannels: [],
		automodInvitesEnabled: false,
		automodInvitesSoftAction: 0,
		automodInvitesHardAction: 'Warning',
		automodInvitesHardActionDuration: null,
		automodInvitesThresholdMaximum: 10,
		automodInvitesThresholdDuration: 60000,
		automodInvitesAllowedCodes: [],
		automodInvitesAllowedGuilds: [],
		automodInvitesIgnoredRoles: [],
		automodInvitesIgnoredChannels: [],
		automodLinksEnabled: false,
		automodLinksSoftAction: 0,
		automodLinksHardAction: 'Warning',
		automodLinksHardActionDuration: null,
		automodLinksThresholdMaximum: 10,
		automodLinksThresholdDuration: 60000,
		automodLinksAllowed: [],
		automodLinksIgnoredRoles: [],
		automodLinksIgnoredChannels: [],
		automodMentionsEnabled: false,
		automodMentionsSoftAction: 0,
		automodMentionsHardAction: 'Warning',
		automodMentionsHardActionDuration: null,
		automodMentionsThresholdMaximum: 10,
		automodMentionsThresholdDuration: 60000,
		automodMentionsIgnoredRoles: [],
		automodMentionsIgnoredChannels: [],
		automodMentionsOverrides: [],
		automodNewlinesEnabled: false,
		automodNewlinesSoftAction: 0,
		automodNewlinesHardAction: 'Warning',
		automodNewlinesHardActionDuration: null,
		automodNewlinesThresholdMaximum: 10,
		automodNewlinesThresholdDuration: 60000,
		automodNewlinesMaximum: 20,
		automodNewlinesIgnoredRoles: [],
		automodNewlinesIgnoredChannels: [],
		automodNoMentionSpamEnabled: false,
		automodNoMentionSpamSoftAction: 0,
		automodNoMentionSpamHardAction: 'Warning',
		automodNoMentionSpamHardActionDuration: null,
		automodNoMentionSpamThresholdMaximum: 10,
		automodNoMentionSpamThresholdDuration: 60000,
		automodNoMentionSpamAlerts: false,
		automodNoMentionSpamMentionsAllowed: 20,
		automodNoMentionSpamTimePeriod: 8,
		automodNoMentionSpamIgnoredRoles: [],
		automodNoMentionSpamIgnoredChannels: [],
		automodWordsEnabled: false,
		automodWordsSoftAction: 0,
		automodWordsHardAction: 'Warning',
		automodWordsHardActionDuration: null,
		automodWordsThresholdMaximum: 10,
		automodWordsThresholdDuration: 60000,
		automodWordsList: [],
		automodWordsIgnoredRoles: [],
		automodWordsIgnoredChannels: [],
		automodZalgoEnabled: false,
		automodZalgoSoftAction: 0,
		automodZalgoHardAction: 'Warning',
		automodZalgoHardActionDuration: null,
		automodZalgoThresholdMaximum: 10,
		automodZalgoThresholdDuration: 60000,
		automodZalgoMaximum: 4,
		automodZalgoIgnoredRoles: [],
		automodZalgoIgnoredChannels: [],
		commandsDisabled: [],
		commandsDisabledChannels: [],
		logsMemberAdd: null,
		logsMemberRemove: null,
		logsMemberNicknameUpdate: null,
		logsMemberUsernameUpdate: null,
		logsMessageDelete: null,
		logsMessageDeleteNsfw: null,
		logsMessageUpdate: null,
		logsMessageUpdateNsfw: null,
		logsPrune: null,
		logsReactionEmojiAdd: null,
		logsReactionEmojiRemove: null,
		logsReactionEmojiIncludeTwemoji: false,
		logsImage: null,
		logsRoleCreate: null,
		logsRoleUpdate: null,
		logsRoleDelete: null,
		logsChannelCreate: null,
		logsChannelUpdate: null,
		logsChannelDelete: null,
		logsEmojiCreate: null,
		logsEmojiUpdate: null,
		logsEmojiDelete: null,
		logsServerUpdate: null,
		logsCommand: null,
		logsSettings: null,
		logsIgnoreAll: [],
		logsIgnoreMessages: [],
		logsIgnoreReactions: [],
		moderationChannel: null,
		moderationTrackBans: false,
		moderationTrackTimeouts: false,
		permissionsUsers: [],
		permissionsRoles: [],
		rolesInitial: [],
		rolesInitialHumans: [],
		rolesInitialRobots: [],
		rolesAdmin: [],
		rolesModerator: [],
		rolesMuted: null,
		rolesPublic: [],
		rolesRemoveInitial: false,
		rolesUniqueRoleSets: [],
		rolesRestrictedReaction: null,
		rolesRestrictedEmbed: null,
		rolesRestrictedEmoji: null,
		rolesRestrictedAttachment: null,
		rolesRestrictedVoice: null,
		stickyRoles: []
	} as const satisfies DefaultGuildData);

	return cachedDefaultGuildSettings;
}

export type DefaultGuildData = Omit<ReadonlyGuildData, 'id'>;
