// This file is automatically generated by `stars codegen`, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
import type { TransformedArguments } from '@wolfstar/http-framework';

// oxfmt-ignore
// prettier-ignore
declare module '@wolfstar/http-framework' {
  interface CommandOptionsRegistry {
    'autodelete disable': {
      channel: TransformedArguments.Channel;
    };
    'autodelete enable': {
      bots?: boolean;
      channel: TransformedArguments.Channel & { type: Extract<TransformedArguments.Channel['type'], 0 | 5> };
      delay?: string;
      embeds?: boolean;
      images?: boolean;
      invites?: boolean;
      links?: boolean;
      mentions?: boolean;
      text?: boolean;
    };
    'autodelete list': {};
    'automod add': {
      rule: string;
      value: string;
    };
    'automod create': {
      name: string;
      type: 'Attachments' | 'Capitals' | 'Invites' | 'Links' | 'Newlines' | 'NoMentionSpam' | 'Words' | 'Zalgo';
    };
    'automod delete': {
      rule: string;
    };
    'automod edit': {
      alert?: boolean;
      delete?: boolean;
      enabled?: boolean;
      log?: boolean;
      maximum?: number;
      mentions?: number;
      minimum?: number;
      period?: number;
      punishment?: 'Warning' | 'Timeout' | 'Mute' | 'Kick' | 'Softban' | 'Ban' | 'VoiceKick';
      'punishment-duration'?: string;
      rename?: string;
      rule: string;
      threshold?: number;
      'threshold-period'?: string;
      warn?: boolean;
    };
    'automod ignore': {
      channel?: TransformedArguments.Channel;
      role?: TransformedArguments.Role;
      rule: string;
    };
    'automod list': {};
    'automod remove': {
      rule: string;
      value: string;
    };
    'automod show': {
      rule: string;
    };
    'autopurge disable': {
      channel: TransformedArguments.Channel;
    };
    'autopurge enable': {
      channel: TransformedArguments.Channel & { type: Extract<TransformedArguments.Channel['type'], 0 | 5> };
      filter?: 'any' | 'user' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'links' | 'invites' | 'images' | 'mentions' | 'embeds' | 'bots' | 'humans' | 'text';
      interval: string;
      value?: string;
    };
    'autopurge list': {};
    'ban add': {
      authored?: boolean;
      'delete-days'?: number;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'ban remove': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'case archive': {
      case: number;
    };
    'case delete': {
      case: number;
    };
    'case edit': {
      case: number;
      duration?: string;
      reason?: string;
    };
    'case list': {
      overview?: boolean;
      page?: number;
      'pending-only'?: boolean;
      show?: boolean;
      type?: 12 | 0 | 1 | 2 | 13 | 9 | 8 | 14 | 7 | 10 | 11 | 3 | 15 | 4 | 5 | 6;
      user?: TransformedArguments.User;
    };
    'case view': {
      case: number;
      show?: boolean;
    };
    'commands': {
      command?: string;
    };
    'dehoist': {};
    'info': {};
    'kick': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'lockdown': {
      action: 'lock' | 'unlock';
      channel?: TransformedArguments.Channel & { type: Extract<TransformedArguments.Channel['type'], 0 | 2 | 4 | 5 | 10 | 11 | 12 | 13 | 15 | 16> };
      duration?: string;
      global?: boolean;
      role?: TransformedArguments.Role;
    };
    'mute add': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'mute create': {
      role?: TransformedArguments.Role;
    };
    'mute remove': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'permission-nodes add': {
      command: string;
      target: TransformedArguments.Mentionable;
      type: 'allow' | 'deny';
    };
    'permission-nodes remove': {
      command: string;
      target: TransformedArguments.Mentionable;
      type: 'allow' | 'deny';
    };
    'permission-nodes reset': {
      target: TransformedArguments.Mentionable;
    };
    'permission-nodes show': {
      target?: TransformedArguments.Mentionable;
    };
    'permissions': {
      'list-all'?: boolean;
      'list-missing'?: boolean;
      show?: boolean;
      user?: TransformedArguments.User;
    };
    'prune age': {
      after?: string;
      age: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune any': {
      after?: string;
      age?: string;
      amount: number;
      attachments?: boolean;
      before?: string;
      bots?: boolean;
      embeds?: boolean;
      endswith?: string;
      humans?: boolean;
      images?: boolean;
      include?: string;
      invites?: boolean;
      links?: boolean;
      match?: string;
      mentions?: boolean;
      pins?: boolean;
      silent?: boolean;
      startswith?: string;
      user?: TransformedArguments.User;
      you?: boolean;
    };
    'prune attachments': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune author': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune bots': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune embeds': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune endswith': {
      after?: string;
      amount: number;
      before?: string;
      endswith: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune humans': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune images': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune includes': {
      after?: string;
      amount: number;
      before?: string;
      include: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune invites': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune links': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune match': {
      after?: string;
      amount: number;
      before?: string;
      match: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune mentions': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune pins': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'prune startswith': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      startswith: string;
      user?: TransformedArguments.User;
    };
    'prune you': {
      after?: string;
      amount: number;
      before?: string;
      silent?: boolean;
      user?: TransformedArguments.User;
    };
    'report': {
      reason: string;
      user: TransformedArguments.User;
    };
    'reports block': {
      user: TransformedArguments.User;
    };
    'reports history': {
      user?: TransformedArguments.User;
    };
    'reports unblock': {
      user: TransformedArguments.User;
    };
    'restrict attachment': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'restrict embed': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'restrict emoji': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'restrict reaction': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'restrict voice': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'role add': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      role: TransformedArguments.Role;
      user: TransformedArguments.User;
    };
    'role remove': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      role: TransformedArguments.Role;
      user: TransformedArguments.User;
    };
    'roles claim': {
      role: TransformedArguments.Role;
    };
    'roles list': {};
    'roles unclaim': {
      role: TransformedArguments.Role;
    };
    'setnickname': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      nickname?: string;
      reason?: string;
      user: TransformedArguments.User;
    };
    'settings server': {};
    'settings user': {};
    'slowmode': {
      duration: string;
    };
    'softban': {
      authored?: boolean;
      'delete-days'?: number;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'sticky-roles add': {
      role: TransformedArguments.Role;
      user: TransformedArguments.User;
    };
    'sticky-roles remove': {
      role: TransformedArguments.Role;
      user: TransformedArguments.User;
    };
    'sticky-roles reset': {
      user: TransformedArguments.User;
    };
    'sticky-roles show': {
      user: TransformedArguments.User;
    };
    'timeout add': {
      authored?: boolean;
      dm?: boolean;
      duration: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'timeout remove': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'unrestrict attachment': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'unrestrict embed': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'unrestrict emoji': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'unrestrict reaction': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'unrestrict voice': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'vmute add': {
      authored?: boolean;
      dm?: boolean;
      duration?: string;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'vmute remove': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'voicekick': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'warn add': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'warn remove': {
      authored?: boolean;
      dm?: boolean;
      image?: TransformedArguments.Attachment;
      reason?: string;
      user: TransformedArguments.User;
    };
    'whois channel': {
      channel?: TransformedArguments.Channel;
    };
    'whois emoji': {
      emoji: string;
    };
    'whois role': {
      role?: TransformedArguments.Role;
    };
    'whois server': {};
    'whois user': {
      user?: TransformedArguments.User;
    };
  }
}
