// Loads the `broker` client option and `container.broker` types, the Stars CLI injects the runtime import:
/// <reference types="@wolfstar/plugin-broker/register" />

import { envParseBoolean, envParseInteger, envParseString } from '@wolfstar/env-utilities';
import { container } from '@wolfstar/http-framework';
import { createBroker, forwardGatewayDispatches, replayGatewayDispatches } from '@wolfstar/plugin-broker';
import { createRedisCache, createRedisSessionStore } from '@wolfstar/plugin-cache';
import { GatewayClient } from '@wolfstar/plugin-gateway';
import { scheduledTasks } from '@wolfstar/plugin-scheduled-tasks';
import { GatewayIntentBits } from 'discord-api-types/v10';
import { parseInternationalizationOptions } from '#lib/i18n/options';
import { WorkerManager } from '#lib/moderation/workers/WorkerManager';
import { bindShardClient, createShardClient } from '#lib/sharder';
import { AnalyticsData } from '#lib/structures/AnalyticsData';
import { isWorker } from '#utils/worker';
import { fileURLToPath } from 'node:url';

export function createClient() {
	const worker = isWorker();
	// Set when a shard manager spawned this process (`SHARDER_ENABLED`), it then only connects its own gateway shards:
	const shard = createShardClient();

	// The threads that run the word filter, started by `loadAll()`:
	container.workers = new WorkerManager();
	container.analytics = envParseBoolean('INFLUX_ENABLED', false) ? new AnalyticsData() : null;

	// The client registers itself as `container.gatewayClient`:
	// oxlint-disable-next-line no-new
	new GatewayClient({
		discordToken: envParseString('DISCORD_TOKEN'),
		discordPublicKey: envParseString('DISCORD_PUBLIC_KEY'),
		intents:
			GatewayIntentBits.GuildModeration |
			GatewayIntentBits.GuildExpressions |
			GatewayIntentBits.GuildInvites |
			GatewayIntentBits.GuildMembers |
			GatewayIntentBits.GuildMessageReactions |
			GatewayIntentBits.GuildMessages |
			GatewayIntentBits.GuildVoiceStates |
			GatewayIntentBits.Guilds |
			GatewayIntentBits.MessageContent,
		...shard?.gatewayOptions,
		// The manager paces the identifies of every shard process:
		gateway: shard ? { buildIdentifyThrottler: () => shard.identifyThrottler } : undefined,
		cache: createRedisCache({ redis: container.redis, prefix: 'wolfstar:cache' }),
		// Keeps the shards' sessions in Redis, so a restart resumes them instead of identifying again:
		sessionStore: createRedisSessionStore({ redis: container.redis, prefix: 'wolfstar:sessions' }),
		api: {
			automaticallyConnect: !worker && envParseBoolean('API_ENABLED', true),
			listenOptions: {
				host: envParseString('API_HOST', '127.0.0.1'),
				port: envParseInteger('API_PORT', 8282)
			},
			origin: envParseString('API_ORIGIN', '*'),
			prefix: envParseString('API_PREFIX', '') || undefined
		},
		i18n: parseInternationalizationOptions(),
		// Runs the tasks the bot schedules, like the end of a lockdown, from the jobs BullMQ keeps in Redis:
		plugins: [scheduledTasks()],
		// `listeners/errors/taskError` logs the task errors, the plugin's own listener would log them twice:
		loadScheduledTaskErrorListeners: false,
		tasks: { queue: 'tasks', bull: { connection: container.redisTasks, prefix: 'wolfstar:bull' } },
		subcommandsAdvanced: {
			nameCommandsAutogenerated: true
		},
		// A worker reads the dispatches from the stream, as a member of a consumer group sharing them with its peers:
		broker: worker
			? {
					redis: container.redis,
					stream: envParseString('BROKER_STREAM', 'wolfstar:events'),
					group: envParseString('BROKER_GROUP', 'workers'),
					consumer: envParseString('BROKER_CONSUMER', 'worker-1'),
					shutdownSignals: ['SIGTERM', 'SIGINT']
				}
			: undefined
	});

	if (shard) bindShardClient(shard, container.gatewayClient);
	if (worker) replayGatewayDispatches(container.broker, container.gatewayClient);

	// Publishes every gateway dispatch onto a Redis stream, for workers that replay them (see `@wolfstar/plugin-broker`):
	if (!worker && envParseBoolean('BROKER_ENABLED', false)) {
		const broker = createBroker({
			redis: container.redis,
			stream: envParseString('BROKER_STREAM', 'wolfstar:events'),
			maxLength: envParseInteger('BROKER_MAX_LENGTH', 100_000)
		});
		forwardGatewayDispatches(container.gatewayClient, broker);
	}

	const srcFolderURL = new URL('..', import.meta.url);
	container.stores.registerPath(fileURLToPath(srcFolderURL));
}

export async function loadAll() {
	await container.redis.connect();
	await container.workers.start();

	if (isWorker()) {
		// No HTTP server and no gateway connection: load the pieces, then start reading the stream:
		await container.gatewayClient.load();
		await container.broker.start();
		return;
	}

	// Loads the pieces, starts the HTTP interactions endpoint, then connects the gateway shards:
	await container.gatewayClient.start({
		listen: {
			address: envParseString('HTTP_ADDRESS', '127.0.0.1'),
			port: envParseInteger('HTTP_PORT', 3000)
		}
	});
}

declare module '@wolfstar/plugin-gateway' {
	// The cache is the Redis one, so the getters computed from it (`member.kickable`, `message.deletable`…) answer a
	// promise. Without this they are typed as plain values, and an `if` on one of them is always true.
	interface GatewayCacheConfig {
		asynchronous: true;
	}
}
