// oxlint-disable no-new
import { envParseBoolean, envParseInteger, envParseString } from '@wolfstar/env-utilities';
import { Client, container } from '@wolfstar/http-framework';
import { MessageBroker, Redis, Cache, RedisOptions } from 'wolfstar-shared';
import * as Sentry from '@sentry/node';
import { fileURLToPath } from 'node:url';

export function createClient(options: ClientOptions = {}) {
	new Client({
		discordToken: envParseString('DISCORD_TOKEN'),
		discordPublicKey: envParseString('DISCORD_PUBLIC_KEY'),
		api: {
			automaticallyConnect: envParseBoolean('API_ENABLED', true),
			listenOptions: {
				host: envParseString('API_HOST', '127.0.0.1'),
				port: envParseInteger('API_PORT', 8282)
			},
			origin: envParseString('API_ORIGIN', '*'),
			prefix: envParseString('API_PREFIX', '') || undefined
		},
		i18n: {
			defaultLanguageDirectory: fileURLToPath(new URL('../locales', import.meta.url)),
			defaultName: 'en-US',
			defaultNS: 'globals'
		},
		subcommandsAdvanced: {
			nameCommandsAutogenerated: true
		}
	});

	container.redis = new Redis({
		...options.redis,
		lazyConnect: true,
		host: envParseString('REDIS_HOST'),
		port: envParseInteger('REDIS_PORT'),
		db: envParseInteger('REDIS_DB'),
		password: envParseString('REDIS_PASSWORD')
	});
	container.cache = new Cache({
		client: container.redis,
		prefix: 's7'
	});
	container.broker = new MessageBroker({
		redis: container.redis,
		stream: envParseString('BROKER_STREAM_NAME'),
		block: envParseInteger('BROKER_BLOCK', 5000),
		max: envParseInteger('BROKER_MAX', 10)
	});

	const srcFolderURL = new URL('..', import.meta.url);
	container.stores.registerPath(fileURLToPath(srcFolderURL));

	// Load in Sentry for error logging
	if (process.env.SENTRY_DSN) {
		Sentry.init({
			dsn: process.env.SENTRY_DSN,
			integrations: [
				Sentry.modulesIntegration(),
				Sentry.functionToStringIntegration(),
				Sentry.linkedErrorsIntegration(),
				Sentry.consoleIntegration(),
				Sentry.httpIntegration({ breadcrumbs: true }),
				Sentry.rewriteFramesIntegration({ root: fileURLToPath(new URL('..', srcFolderURL)) })
			]
		});
	}
}

export async function loadAll() {
	await container.redis.connect();
	await container.client.load();
	await container.client.listen({
		address: envParseString('HTTP_ADDRESS', '127.0.0.1'),
		port: envParseInteger('HTTP_PORT', 3000)
	});
}

export interface ClientOptions {
	redis?: Omit<RedisOptions, 'lazyConnect' | 'host' | 'port' | 'db' | 'password'>;
}

declare module '@sapphire/pieces' {
	interface Container {
		broker: MessageBroker;
		cache: Cache;
		redis: Redis;

		// db: DbSet;
		// schedule: ScheduleManager;
		// settings: SettingsManager;
		// workers: WorkerManager;
	}
}
