import { writeFile } from 'node:fs/promises';

const sourceUrl = 'https://raw.githubusercontent.com/Discord-AntiScam/scam-links/main/list.json';

// Download the list of Discord-AntiScam, an array of hostnames
const response = await fetch(sourceUrl);
if (!response.ok) throw new Error(`The list of phishing links answered ${response.status}.`);

const source = await response.json();
if (!Array.isArray(source)) throw new TypeError('The list of phishing links is not an array.');

// Read the hostnames as the bot matches them (lowercase, without `www.`), and drop what could not be one: the entries
// are written into a source file
const hostnames = new Set();
for (const entry of source) {
	if (typeof entry !== 'string') continue;

	const lowered = entry.trim().toLowerCase().replace(/\.$/, '');
	const hostname = lowered.startsWith('www.') ? lowered.slice(4) : lowered;
	if (/^[a-z0-9¡-￿._-]+$/.test(hostname)) hostnames.add(hostname);
}

// A list that lost most of its entries is a broken download, not an update
if (hostnames.size < 1000) throw new Error(`The list of phishing links only has ${hostnames.size} hostnames.`);

// Define header and footer, which will wrap the content
const header = `// Autogenerated file from Discord-AntiScam, source:\n// ${sourceUrl}\n\nexport const PhishingHostnames = [\n`;
const footer = '\n];\n';
const sorted = [...hostnames].sort();
const content = sorted.map((hostname, index) => `\t'${hostname}'${index === sorted.length - 1 ? '' : ','}`).join('\n');

const outputFile = new URL('../projects/bot/src/lib/utilities/Links/PhishingHostnames.ts', import.meta.url);

await writeFile(outputFile, header + content + footer);
