version: '2.4'
services:
  postgres:
    container_name: postgres
    image: 'skyrabot/postgres:latest'
    networks:
      - wolfstar
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  redis:
    command: 'redis-server --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - wolfstar
    ports:
      - '8287:8287'
    restart: always

  wolfstar-bot:
    build:
      context: ../../
      dockerfile: ../bot/Dockerfile
    container_name: wolfstar-bot
    depends_on:
      - redis
      - postgres
    env_file:
      - ../bot/src/.env.development
      - ../bot/src/.env.development.local
    image: 'ghcr.io/wolfstar-project/wolfstar-bot:latest'
    networks:
      - wolfstar
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

  wolfstar-gateway:
    build:
      context: ../../
      dockerfile: ../gateway/Dockerfile
    container_name: wolfstar-gateway
    env_file:
      - ../gateway/src/.env.development
      - ../gateway/src/.env.development.local
    image: 'ghcr.io/wolfstar-project/wolfstar-gateway:latest'
    networks:
      - wolfstar
    restart: always
    tty: true

volumes:
  postgres-data:
    external: true

networks:
  wolfstar:
