# needed to securely identify the workflow
name: autofix.ci

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    code:
        runs-on: ubuntu-24.04-arm

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  fetch-depth: 0

            - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
              with:
                  node-version: lts/*

            - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6
              name: Install pnpm

            - name: Install dependencies (root only, no scripts)
              run: pnpm install --filter . --ignore-scripts

            - name: 🔠 Fix lint errors
              run: pnpm run lint:fix

            - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
