# needed to securely identify the workflow
name: autofix.ci

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    code:
        runs-on: blacksmith-4vcpu-ubuntu-2404-arm

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  fetch-depth: 0

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: lts/*

            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
              name: Install pnpm

            - name: Install dependencies (root only, no scripts)
              run: pnpm install --filter . --ignore-scripts

            - name: 🔠 Fix lint errors
              run: pnpm run lint:fix

            - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
