# needed to securely identify the workflow
name: autofix.ci

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    code:
        runs-on: ubuntu-24.04-arm

        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  fetch-depth: 0

            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: lts/*

            - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6
              name: Install pnpm

            - name: Install dependencies (root only, no scripts)
              run: pnpm install --filter . --ignore-scripts

            - name: 🔠 Fix lint errors
              run: pnpm run lint:fix

            - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
