name: Publish stable image WolfStar

on:
    workflow_dispatch:
        inputs:
            commit:
                type: string
                required: true
                description: The SHA256 commit hash to publish

permissions:
    contents: read
    packages: write

env:
    HUSKY: 0

jobs:
    publish:
        name: Publish WolfStar Latest image to GHCR
        uses: wolfstar-project/.github/.github/workflows/reusable-publish-image.yml@main
        secrets: inherit
        with:
            enablePlatforms: true
            commitHash: ${{ github.event.inputs.commit }}
            tag: stable
            platforms: >-
                [{"platform": "linux/amd64", "runner": "ubuntu-latest"}, {"platform": "linux/arm64", "runner": "ubuntu-latest"}]
